### ISSUE TITLE
Bug，解析Byte类型的枚举会报强制转换类型错误

### ISSUE THREAD

**Issue by blueberryWT** [qcwgithub/qjsbunitynew_bridge#1]
在binding一个第三方类库的时候，发现有一个枚举类型是byte类型，在转换的时候报错了，原因如下

CSWrapGenerator:138行左右 把enum value强转成了int，如果这个value是byte居然会报错

所以修改如下：

var value = field.GetValue(null);
                Type enumType = Enum.GetUnderlyingType(value.GetType());
                if (enumType == typeof(System.Byte))
                {
                    tfClass.Add("{0} = {1},", field.Name, (byte)value);
                }
                else
                {
                    tfClass.Add("{0} = {1},", field.Name, (int)value);
                }

**Comment by qcwgithub** [comment]
我改成
`System.Convert.ToInt64(field.GetValue(null))`
