### ISSUE TITLE
转换Dotween的DG.Tweening.ShortcutExtensions对象时，生成的_G文件报错

### ISSUE THREAD

**Issue by blueberryWT** [qcwgithub/qjsbunitynew_bridge#2]
尝试转换DoTween的DG.Tweening.ShortcutExtensions对象
转换之后，生成相应的_G文件报错
大概分为以下几个类型：
1.转换的参数类型类型不匹配
2.转换的参数个数不匹配
3.找不到对应的方法

**Comment by qcwgithub** [comment]
麻烦把必要的文件发给我，重现Bug

**Comment by qcwgithub** [comment]
查清楚了，这个问题不存在，不需要解决。
