### ISSUE TITLE
Gen Bindings时，如果参数中含有ref List<string> 这种格式，转换出来的_G.cs文件有错误

### ISSUE THREAD

**Issue by blueberryWT** [qcwgithub/qjsbunitynew_bridge#3]

**Comment by blueberryWT** [comment]
Gen Bindings时，如果参数中含有ref List<string> 这种格式，转换出来的_G.cs文件有错误
定义：public void TestRefMethod( ref List<string> _list)
转换后：List的声明格式有误
`System.Collections.Generic.List`1[[System.String, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] arg0 = (System.Collections.Generic.List`1[[System.String, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]])JSMgr.datax.getObject((int)JSApi.GetType.ArgRef);`

**Comment by qcwgithub** [comment]
```
// 应该先 type = type.GetElementType();
if (type.IsByRef)
    type = type.GetElementType();

    bool isgp = type.IsGenericParameter;
    bool cgt = type.ContainsGenericParameters;
    bool gt = type.IsGenericType;
    bool gtd = type.IsGenericTypeDefinition;
```

**Comment by qcwgithub** [comment]
不过绝对不能导出带 ref List 参数的函数，因为 List 是 Js 实现，不可能通过 C# 创建再返回给 Js。
（导出可以，不能使用）

**Comment by qcwgithub** [comment]
可以在 `GeneratorHelp.CreateTypeInfo` 中把这种函数排除掉。一般来说，任何的 Js 类型都不应该跑到 C# 中去。
